#!/usr/bin/env bash
# packaging/build_licenses.sh - packaging/THIRD_PARTY_LICENSES.txt を作る（Python 2 つ・Electron）
# collect_licenses.py は akasyx_search の packaging/ と同じもの。--exclude は build_python.sh の除外と揃える
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SIB="$(cd "$ROOT/.." && pwd)"
OUT="$ROOT/packaging/THIRD_PARTY_LICENSES.txt"
COLLECT="$ROOT/packaging/collect_licenses.py"
{
  echo "akasyx Duplicate Detector — third-party notices / サードパーティのライセンス表記"
  echo "Generated by packaging/build_licenses.sh on $(date -u +%Y-%m-%d)"
  echo
  (cd "$ROOT/detector" && uv run --inexact --no-dev python "$COLLECT" "akasyx-detector (Python)")
  (cd "$SIB/akasyx_crawler/crawler" && uv run --inexact --no-dev --extra meta python "$COLLECT" "akasyx-crawler (Python)" --exclude mutagen,pillow-heif)
  echo
  echo "=============================================================================="
  echo "Electron / Chromium — see LICENSE.electron.txt and LICENSES.chromium.html inside the app"
  echo "=============================================================================="
  echo "The UI has no npm production dependencies."
} > "$OUT"
echo "$OUT ($(wc -c < "$OUT") bytes)"
